server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: itstadmin
    password: initialP@$$w0rd
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false
  boot:
    message: Hello, Employee service updated

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

management:
  health:
    circuitbreaker:
      enable: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      EMPLOYEE-SERVICE:
        registerHealthIndicator: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      EMPLOYEE-SERVICE:
        registerHealthIndicator: true
        maxRetryAttempts: 5
        waitDuration: 1s
