server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: password
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false
  boot:
    message: Hello, Employee service updated

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
